OrderViewer.Web/Models/OrderItems.cs
namespace OrderViewer.Web.Models
{
    public class OrderItems
    {
        public Guid OrderId { get; set; }
        public List<OrderDetails> Items { get; set; }
    }

    public class OrderDetails 
    {
        public string Name { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
    }
}

OrderViewer.Web/Controllers/OrderViewerController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using OrderViewer.Web.Interfaces;
using OrderViewer.Web.Models;

namespace OrderViewer.Web.Controllers
{
    public class OrderViewerController : Controller
    {

        private readonly IOrderService _orderService;

        public OrderViewerController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        [HttpGet]
        public async Task<IActionResult> GetOrderItems(Guid orderId)
        {
            var allItems = await _orderService.GetProductsByOrderId(orderId);
           
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            { 
                return PartialView("_OrderItems", allItems.Result);
            }
            return PartialView("_OrderItems", allItems.Result);
        }
        
        public async Task<IActionResult> OrderViewerIndex([FromQuery] OrderFilter orderFilter)
        {
            // Ensure defaults
            orderFilter.PageNumber = orderFilter.PageNumber <= 0 ? 1 : orderFilter.PageNumber;
            orderFilter.PageSize = orderFilter.PageSize <= 0 ? 10 : orderFilter.PageSize;
            
            var orders = await _orderService.GetOrdersAsync(orderFilter);

            ViewBag.Filter = orderFilter;
            ViewBag.StatusOptions = Enum.GetValues(typeof(OrderStatus))
                .Cast<OrderStatus>()
                .Select(s => new SelectListItem
                {
                    Value = s.ToString(),
                    Text = s.ToString()
                })
                .ToList();

            if (orders == null) 
            {
                return View(new PaginatedOrders());
            }
            return View(orders);
        }

        [HttpGet]
        public async Task<IActionResult> OrderViewerData([FromQuery] OrderFilter orderFilter)
        {
            // Ensure defaults
            orderFilter.PageNumber = orderFilter.PageNumber <= 0 ? 1 : orderFilter.PageNumber;
            orderFilter.PageSize = orderFilter.PageSize <= 0 ? 10 : orderFilter.PageSize;

            var orders = await _orderService.GetOrdersAsync(orderFilter);

            //render partials as string
            var tableHtml = await this.RenderViewAsync("_OrderTablePartial", orders, true);
            var paginationHtml = await this.RenderViewAsync("_PaginatingPartial", orders, true);

            //build summary
            var summary = new
            {
                count = orders?.Items.Count ,
                grandTotal = orders?.Items.Sum(o => o.Total)
            };

            return Json(new
            {
                table = tableHtml,
                pagination = paginationHtml,
                summary
            });
        }

        [HttpGet]
        public async Task<IActionResult> GetOrderById(Guid orderId)
        { 
            var order = await _orderService.GetOrderByIdAsync(orderId);
            return Json(order);
        }

        public async Task<IActionResult> OrderCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> OrderCreate(OrderDto model)
        {
            if (ModelState.IsValid)
            {
                ResponseDto<OrderDto>? response = await _orderService.CreateOrderAysnc(model);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(OrderCreate));
                }
            }
            return View(model);
        }

        [HttpPatch]
        public async Task<IActionResult> OrderUpdate(OrderDto model)
        {
            if (ModelState.IsValid)
            {
                ResponseDto<OrderDto>? response = await _orderService.UpdateOrderAysnc(model);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(OrderViewerIndex));
                }
            }
            return View(model);
        }

        [HttpPost("/OrderViewer/MarkOrderPaid/{orderId}")]
        public async Task<IActionResult> MarkOrderAsPaid(string orderId)
        {
            if (string.IsNullOrEmpty(orderId))
                return BadRequest(new { success = false, message = "Order ID required" });

            var order = await _orderService.GetOrderByIdAsync(Guid.Parse(orderId));
            if (order == null)
                return NotFound(new { success = false, message = "Order not found" });

            if (order.Status == OrderStatus.Paid.ToString())
                return Json(new { success = true, message = "Order already paid" });


            var mappedOrder = new OrderDto
            {
                OrderId = order.OrderId,
                Customer = order.Customer,
                Status = OrderStatus.Paid.ToString(),
                CreatedAt = order.CreatedAt,
                Total = order.Total
            };
            var results = await _orderService.UpdateOrderAysnc(mappedOrder);

            return Json(new { success = true, message = "Order marked as paid" });
        }

    }
}

OrderViewer.Web/Views/OrderViewer/OrderCreate.cshtml
@model OrderDto

@{
	var filter = ViewBag.Filter as OrderDto;
}

<form asp-action="OrderCreate">
	<br />
	<div class="container border p-3">
		<h1 class="text-black text-center">Create Order</h1>
		<hr />
		<div class="row">
			<div class="col-2">
				<label class="control-label pt-2" style="font-size:20px;">Order ID</label>
			</div>
			<div class="col-10 pb-3">
				<input class="form-control" asp-for="OrderId" />
				<span asp-validation-for="OrderId" class="text-danger"></span>
			</div>
			<div class="col-2">
				<label class="control-label pt-2" style="font-size:20px;">Customer</label>
			</div>
			<div class="col-10 pb-3">
				<input class="form-control" asp-for="Customer" />
				<span asp-validation-for="Customer" class="text-danger"></span>
			</div>
			<div class="col-2">
				<label class="control-label pt-2" style="font-size:20px;">Status</label>
			</div>
			<div class="col-10 pb-3">
				<input class="form-control" asp-for="Status" />
				<span asp-validation-for="Status" class="text-danger"></span>
			</div>
			<div class="col-2">
				<label class="control-label pt-2" style="font-size:20px;">Total</label>
			</div>
			<div class="col-10 pb-3">
				<input class="form-control" asp-for="Total" type="number" step="any" />
				<span asp-validation-for="Total" class="text-danger"></span>
			</div>
			<div class="col-2">
				<label class="control-label pt-2" style="font-size:20px;">Order Date & Time</label>
			</div>
			<div class="col-10 pb-3">
				<input class="form-control" asp-for="CreatedAt" type="datetime-local" />
				<span asp-validation-for="CreatedAt" class="text-danger"></span>
			</div>

			<div class="col-3 offset-2">
				<a class="btn-primary btn form-control" asp-action="OrderViewerIndex">Back to List</a>
			</div>
			<div class="col-3">
				<input type="submit" value="Create" class="btn btn-success form-control" />

			</div>

		</div>
	</div>

</form>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

OrderViewer.Web/Views/OrderViewer/OrderViewerIndex.cshtml
@model PaginatedOrders
@{
    var filter = ViewBag.Filter as OrderFilter;
}

<div class="row col-12">
		<form id="filter-form" method="get">
			<div class="row mb-3">
				<div class="col-12 d-flex justify-content-between align-items-center flex-wrap">
					<div class="d-flex flex-wrap gap-3">
						<div>
							<label for="fromDate">From Date</label>
							<input type="date" id="fromDate" name="FromDate" class="form-control"
								   value="@(filter?.FromDate?.ToString("yyyy-MM-ddHH:mm:ss"))" />
						</div>
						<div>
							<label for="toDate">To Date</label>
							<input type="date" id="toDate" name="ToDate" class="form-control"
							   value="@(filter?.ToDate?.ToString("yyyy-MM-ddHH:mm:ss"))" />
						</div>
					</div>
					<div id="order-summary" class="text-end mt-3 mt-md-0">
						<div><strong>Filtered Orders:</strong> <span id="order-count">0</span></div>
						<div><strong>Grand Total:</strong> <span id="order-total">0</span></div>
					</div>
				</div>
			</div> 
			<br />
			<hr />
			<div class="d-flex align-items-center gap-2 mb-3">
				<label for="pageSize">Rows per page:</label>
				<select id="pageSize" name="PageSize" class="form-select" style="width: auto;">
					@foreach (var size in new[] { 5, 10, 20, 30 })
					{
					var selected = (filter?.PageSize ?? 10) == size;
						<option value="@size" selected="@selected" >@size</option>
					}
				</select>
			</div>
		<div 
			id="table-spinner" 
			style="display:none;
				position:absolute; top:0; left:0; right:0; bottom:0;
				background:rgba(255,255,255,0.7);
				align-items:center; 
				justify-content:center;
				z-index:10;"
			>
				<div class="spinner-border text-primary" role="status">
					<span class="visually-hidden">Loading...</span>
				</div>
			</div>

			<table class="table" id="orders-table">
				<thead>
					<!--Header row -->
					<tr>
						<th>Order Id</th>
						<th>Customer</th>
						<th>Status</th>
						<th>Total <i class="fa fa-sort sort-icon" data-column="total" aria-hidden="true"></i></th>
						<th>Created Date <i class="fa fa-sort sort-icon" data-column="createdAt" aria-hidden="true"></i></th>
					</tr>
					<!--Filter row-->
					<tr>
						<th>
							<input type="text" name="OrderId" value="@filter?.OrderId" class="form-control" placeholder="Order ID" />
						</th>
						<th>
							<input type="text" name="Customer" value="@filter?.Customer" class="form-control" placeholder="Customer" />
						</th>
						<th>
							<select name="Status" class="form-control">
								<option value="">All</option>
								@foreach (var status in Enum.GetValues(typeof(OrderStatus)).Cast<OrderStatus>())
								{
									var selected = filter?.Status == status.ToString() ? true : false;
									<option value="@status" selected="@selected">@status</option>
								}
							</select>
						</th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<!--Orders View-->
				<tbody id="results-container">
						@await Html.PartialAsync("_OrderTablePartial", Model)
				</tbody>
			</table>
			<!--Pagination view-->
			<div id="pagination-container">
				@await Html.PartialAsync("_PaginatingPartial", Model)
			</div>
		</form>	
</div>
@* <div class="row col-12">
	<div class="text-end">
		<a class="btn btn-outline-primary" asp-controller="OrderViewer" asp-action="OrderCreate">
			<i class="bi bi-plus-square"></i>
			Create New Order
		</a>
	</div>
</div> *@
@section Scripts {
	<script src="~/js/OrderItems.js"></script>
	<script src="~/js/views.js"></script>
}

OrderViewer.Web/Views/OrderViewer/_OrderItems.cshtml
@model ProductDto

<table class="table table-sm mb-0">
	<thead>
		<tr>
			<th>Item</th>
			<th>Qty</th>
			<th>Unit Price</th>
			<th>Total</th>
		</tr>
	</thead>
	<tbody>
		@if (Model?.Products != null && Model.Products.Any())
		{
			@foreach (var products in Model.Products)
			{
				<tr>
					<td>@products.Name</td>
					<td>@products.Quantity</td>
					<td>@products.UnitPrice.ToString("C")</td>
					<td>@((products.Quantity * products.UnitPrice).ToString("C"))</td>
				</tr>
			}
		}
	</tbody>
</table>

OrderViewer.Web/Views/OrderViewer/_OrderTablePartial.cshtml
<div>
	<div>
		@foreach (var order in Model.Items)
		{
			var isPaid = order.Status == OrderStatus.Paid.ToString();
			var isCancelled = order.Status == OrderStatus.Cancelled.ToString();

			<tr style="cursor: pointer;" 
				data-order-id="@order.OrderId" 
				class="order-row @(isPaid ? "paid-row" : isCancelled ? "cancelled-row" : "") " 
				id="order-@order.OrderId"
			>
				<td data-label="OrderId">@order.OrderId</td>
				<td data-label="Customer">@order.Customer</td>
				<td data-label="Status">@order.Status</td>
				<td data-label="Total">@((order.Total).ToString("c"))</td>
				<td data-label="CreatedAt">@order.CreatedAt</td>
				<td data-label="Paid">
					@if (order.Status != OrderStatus.Cancelled.ToString())
					{
						<input type="checkbox" class="mark-paid-checkbox" data-order-id="@order.OrderId" @(isPaid ? "checked disabled" : "") />
					}
				</td>
			</tr>
			<tr id="order-items-@order.OrderId" style="display: none; background-color: #f9f9f9;">
				<td colspan="5" id="order-items-content-@order.OrderId">
					<em>Loading...</em>
				</td>
			</tr>
		}
	</div>
</div>

OrderViewer.Web/Views/OrderViewer/_PaginatingPartial.cshtml
<nav>
	<ul class="pagination">
		@for (int i = 1; i <= Model.TotalPages; i++)
		{
			<li class="page-item @(i == Model.CurrentPage ? "active" : "")">
				<a href="#"
				   class="page-link"
				   data-page="@i">
					@i
				</a>
			</li>
		}
	</ul>
</nav>